### ISSUE TITLE
Error When Installing Using Dev Tools 

### ISSUE THREAD

**Issue by josep2** [JulianHill/ThinkToStartR#1]
I am on R 3.1.0 OSX Mavericks. When using Devtools to install via github I get this error:

Error in contrib.url(repos, "source") : 
  trying to use CRAN without setting a mirror
Error : unable to load R code in package 'ThinkToStartR'
ERROR: lazy loading failed for package 'ThinkToStartR'
- removing '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/ThinkToStartR'
  Error: Command failed (1)

Thanks

**Comment by JulianHill** [comment]
Hey,

please try
install.packages("Rfacebook")
in your R console before you use the devtools install command.
Does this change anything?

Regards

**Comment by josep2** [comment]
Thanks for the response. 

The same error was thrown when following this step.

**Comment by JulianHill** [comment]
Ok, I just updated the depends parameter in the package. Please try to install it again with:

`require(devtools) #install if necessary (install.packages("devtools")`

`dev_mode(on=T)`
`install_github("ThinkToStartR",username="JulianHill",subdir="ThinkToStartR")`

Is there a new respond?

Regards

**Comment by josep2** [comment]
That did the trick. Thank you!
